### ISSUE TITLE
训练数据集加载问题

### ISSUE THREAD

**Issue by aoe-wyb** [YuZheng9/C2PNet#10]
您好！我在使用您提供的ITS.lmdb文件训练时，出现以下问题
![image](https://user-images.githubusercontent.com/62412181/235357405-6546f3cf-015c-4ef9-b7d1-d184680eb9ee.png)
怀疑是ITS.lmdb文件的问题，希望能得到你的解答。

**Comment by YuZheng9** [comment]
> 您好！我在使用您提供的ITS.lmdb文件训练时，出现以下问题 ![image](https://user-images.githubusercontent.com/62412181/235357405-6546f3cf-015c-4ef9-b7d1-d184680eb9ee.png) 怀疑是ITS.lmdb文件的问题，希望能得到你的解答。

你好，我在百度网盘重新更新了数据，给您带来不便深感抱歉。

**Comment by aoe-wyb** [comment]
十分感谢您的回信。




yabo_wu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuZheng9/C2PNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuZheng9/C2PNet] 训练数据集加载问题 (Issue #10)





  
您好！我在使用您提供的ITS.lmdb文件训练时，出现以下问题  怀疑是ITS.lmdb文件的问题，希望能得到你的解答。
  
你好，我在百度网盘重新更新了数据，给您带来不便深感抱歉。

**Comment by aoe-wyb** [comment]
您好：
感谢您上一次的解答！
我现在又出现了一个问题，困扰了我几天，我用您更新的ITS.lmdb文件训练，出现了如下的情况：
迭代3540次，psnr只有16。对比了一下两次ITS数据集的大小，第一次是122G，第二次给的是89G。



这是我的训练设置

以及：



希望得到您的回信，祝您科研顺利。


yabo_wu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yabo_wu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 下午4:32
***@***.***&gt;;

主题:&nbsp;回复： [YuZheng9/C2PNet] 训练数据集加载问题 (Issue #10)



十分感谢您的回信。




yabo_wu
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YuZheng9/C2PNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuZheng9/C2PNet] 训练数据集加载问题 (Issue #10)





  
您好！我在使用您提供的ITS.lmdb文件训练时，出现以下问题  怀疑是ITS.lmdb文件的问题，希望能得到你的解答。
  
你好，我在百度网盘重新更新了数据，给您带来不便深感抱歉。
