### ISSUE TITLE
真实数据去雾

### ISSUE THREAD

**Issue by tongchangD** [YuZheng9/C2PNet#12]
您好，
请问您尝试过在真实数据上做去雾吗?或者说您的模型有在真实数据上测试过吗？

我使用HSTS，使用您发布的模型，发现效果并不佳，似乎没有变化，或者说生成图效果更差。
如下示例

|原图|c2pnet效果图|模型|
|-|-|-|
|![MLS_Google_585](https://github.com/YuZheng9/C2PNet/assets/36293393/9b9384c1-9d78-48ec-b530-f6714679614d)|![MLS_Google_585 _c2pnet](https://github.com/YuZheng9/C2PNet/assets/36293393/dab758f2-678a-42c4-ab68-e3870ca21804)|its|
|![MLS_Google_585](https://github.com/YuZheng9/C2PNet/assets/36293393/8567e80a-1d90-41aa-ad2e-a26f2b7392b9)|![MLS_Google_585 _c2pnet](https://github.com/YuZheng9/C2PNet/assets/36293393/b206a1ae-0ed2-43b9-9766-b9fa5bc5531a)|ots|

说实话，感觉有些拉胯。

paperwithcode 上 霸榜单图像去噪 是真的吗?

无恶意，纯只是想了解下情况 

祝好，
    tongchangD

**Comment by Cuihaoranabc** [comment]
请问下面其他的两种方法是什么?

**Comment by buhuizuodanb** [comment]
请问下面这种方法是什么？

**Comment by YuZheng9** [comment]
> 您好， 请问您尝试过在真实数据上做去雾吗?或者说您的模型有在真实数据上测试过吗？
> 
> 我使用HSTS，使用您发布的模型，发现效果并不佳，似乎没有变化，或者说生成图效果更差。 如下示例
> 
> 原图	c2pnet效果图	模型
> ![MLS_Google_585](https://user-images.githubusercontent.com/36293393/237561236-9b9384c1-9d78-48ec-b530-f6714679614d.png)	![MLS_Google_585 _c2pnet](https://user-images.githubusercontent.com/36293393/237561300-dab758f2-678a-42c4-ab68-e3870ca21804.png)	its
> ![MLS_Google_585](https://user-images.githubusercontent.com/36293393/237561697-8567e80a-1d90-41aa-ad2e-a26f2b7392b9.png)	![MLS_Google_585 _c2pnet](https://user-images.githubusercontent.com/36293393/237561746-b206a1ae-0ed2-43b9-9766-b9fa5bc5531a.png)	ots
> 说实话，感觉有些拉胯。
> 
> paperwithcode 上 霸榜单图像去噪 是真的吗?
> 
> 无恶意，纯只是想了解下情况
> 
> 祝好， tongchangD

你好，事实上，现在的大多数专注于合成图像数据集的去雾方法（也就是你看的paperwithcode榜单上的方法）或多或少都有这样的问题，研究从合成图像到真实图像的泛化或是真实图像去雾也是这个领域非常热门的一个问题（事实上cvpr2023收录的更多也是这种论文）。此外我们的模型在经过微调后，在fattal‘s dataset也有不错的视觉效果。
<img width="849" alt="image" src="https://github.com/YuZheng9/C2PNet/assets/59441984/58b7191f-8167-4240-9bd7-62851cd35bab">

**Comment by YuZheng9** [comment]
> 

下面的那个方法是我们在户外图像数据集预训练的模型

**Comment by tongchangD** [comment]
> 请问下面这种方法是什么？

作者的两个模型中的其中一个，最右侧有注释，我那个表是三列的

**Comment by tongchangD** [comment]
@YuZheng9  好的，谢谢您的回复，我最近在调研去雾算法，主要是想应用在深雾中，但是我发现现有的算法基本都很差，甚至有部分还不如[ACE](https://blog.csdn.net/qq_42627691/article/details/121052475)，很多模型的情况是模型去雾图与原雾图相差无几（眼睛感受不到变化的这种）。
请问，对待那种深雾浓雾下的图像（能见度非常低的雾图）去雾，您有推荐吗

**Comment by tongchangD** [comment]
请问对于真实数据去雾，在做合成雾的时候，除了有[RGB和模拟大气散射模型](https://github.com/RQ-Wu/RIDCP_dehazing/issues/10)来添加雾，还有其他比价好的方案来添加雾气吗，请问有试过利用Photoshop来合成真实雾最终用于去雾吗

**Comment by cecret3350** [comment]
> > 您好， 请问您尝试过在真实数据上做去雾吗?或者说您的模型有在真实数据上测试过吗？
> > 我使用HSTS，使用您发布的模型，发现效果并不佳，似乎没有变化，或者说生成图效果更差。 如下示例
> > 原图	c2pnet效果图	模型
> > ![MLS_Google_585](https://user-images.githubusercontent.com/36293393/237561236-9b9384c1-9d78-48ec-b530-f6714679614d.png)	![MLS_Google_585 _c2pnet](https://user-images.githubusercontent.com/36293393/237561300-dab758f2-678a-42c4-ab68-e3870ca21804.png)	its
> > ![MLS_Google_585](https://user-images.githubusercontent.com/36293393/237561697-8567e80a-1d90-41aa-ad2e-a26f2b7392b9.png)	![MLS_Google_585 _c2pnet](https://user-images.githubusercontent.com/36293393/237561746-b206a1ae-0ed2-43b9-9766-b9fa5bc5531a.png)	ots
> > 说实话，感觉有些拉胯。
> > paperwithcode 上 霸榜单图像去噪 是真的吗?
> > 无恶意，纯只是想了解下情况
> > 祝好， tongchangD
> 
> 你好，事实上，现在的大多数专注于合成图像数据集的去雾方法（也就是你看的paperwithcode榜单上的方法）或多或少都有这样的问题，研究从合成图像到真实图像的泛化或是真实图像去雾也是这个领域非常热门的一个问题（事实上cvpr2023收录的更多也是这种论文）。此外我们的模型在经过微调后，在fattal‘s dataset也有不错的视觉效果。 <img alt="image" width="849" src="https://user-images.githubusercontent.com/59441984/237628471-58b7191f-8167-4240-9bd7-62851cd35bab.png">

您好，可以请教一下微调的方式吗？

**Comment by cecret3350** [comment]
@YuZheng9 您好，可以请教一下微调的方式吗？

**Comment by tongchangD** [comment]
@YuZheng9  您好，请问可以告知一下 n1_path、n2_path、n3_path、n4_path、n5_path、n6_path 这些数据的意义吗，或者说从何而来？
如果是想训练自己的数据，那我该如何生成这些文件？
祝好
tongchangD

**Comment by chartgod** [comment]
![Base_C2PNet](https://github.com/YuZheng9/C2PNet/assets/117190078/85fda932-c5cc-43da-89b3-4988b224376f)
![test2](https://github.com/YuZheng9/C2PNet/assets/117190078/2be9b791-d041-43c4-b9bc-398dd9c5b7f7)
![OTS_C2PNet](https://github.com/YuZheng9/C2PNet/assets/117190078/946c1a7e-5899-4545-821e-b71e889aaedb)
可能是因为没有使用pkl文件，所以照片是这样的。

trained_data -> OTS.我用过pkl，结果也差不多。

我遗漏的内容是net.load_state_dict(checkpoint['model'])，在哪个部分出了问题呢？

**Comment by tongchangD** [comment]
@chartgod  please show your code  
你随便三张图，对不起，真不知道你想表达的是什么，作者给的代码非常完善了，是完全能够运行的

你都不加载模型参数，

你还会发现每次运行结果都是不一样的。

**Comment by chartgod** [comment]
> @chartgod 코드를 보여주세요 .
> 
> 你都不加载模型参数,
> 
> 你还会发现每次运行结果都是不一样的.

import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image

def default_conv(in_channels, out_channels, kernel_size, bias=True):
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=(kernel_size // 2), bias=bias)


class CALayer(nn.Module):
    def __init__(self, channel):
        super(CALayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ca = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PDU(nn.Module):  # physical block
    def __init__(self, channel):
        super(PDU, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ka = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )
        self.td = nn.Sequential(
            default_conv(channel, channel, 3),
            default_conv(channel, channel // 8, 3),
            nn.ReLU(inplace=True),
            default_conv(channel // 8, channel, 3),
            nn.Sigmoid()
        )

    def forward(self, x):
        a = self.avg_pool(x)
        a = self.ka(a)
        t = self.td(x)
        j = torch.mul((1 - t), a) + torch.mul(t, x)
        return j


class Block(nn.Module):  # origin
    def __init__(self, conv, dim, kernel_size, ):
        super(Block, self).__init__()
        self.conv1 = conv(dim, dim, kernel_size, bias=True)
        self.act1 = nn.ReLU(inplace=True)
        self.conv2 = conv(dim, dim, kernel_size, bias=True)
        self.calayer = CALayer(dim)
        self.pdu = PDU(dim)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x
        res = self.conv2(res)
        res = self.calayer(res)
        res = self.pdu(res)
        res += x
        return res


class Group(nn.Module):
    def __init__(self, conv, dim, kernel_size, blocks):
        super(Group, self).__init__()
        modules = [Block(conv, dim, kernel_size) for _ in range(blocks)]
        modules.append(conv(dim, dim, kernel_size))
        self.gp = nn.Sequential(*modules)

    def forward(self, x):
        res = self.gp(x)
        res += x
        return res


class C2PNet(nn.Module):
    def __init__(self, gps, blocks, conv=default_conv):
        super(C2PNet, self).__init__()
        self.gps = gps
        self.dim = 64
        kernel_size = 3
        pre_process = [conv(3, self.dim, kernel_size)]
        assert self.gps == 3
        self.g1 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g2 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g3 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.ca = nn.Sequential(*[
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(self.dim * self.gps, self.dim // 16, 1, padding=0),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.dim // 16, self.dim * self.gps, 1, padding=0, bias=True),
            nn.Sigmoid()
        ])
        self.pdu = PDU(self.dim)

        post_precess = [
            conv(self.dim, self.dim, kernel_size),
            conv(self.dim, 3, kernel_size)]

        self.pre = nn.Sequential(*pre_process)
        self.post = nn.Sequential(*post_precess)

    def forward(self, x1):
        x = self.pre(x1)
        res1 = self.g1(x)
        res2 = self.g2(res1)
        res3 = self.g3(res2)
        w = self.ca(torch.cat([res1, res2, res3], dim=1))
        w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]
        out = w[:, 0, ::] * res1 + w[:, 1, ::] * res2 + w[:, 2, ::] * res3
        out = self.pdu(out)
        x = self.post(out)
        return x + x1

# Load the C2PNet model
net = C2PNet(gps=3, blocks=19)

# Load the checkpoint
checkpoint_path = 'C:/C2PNet-main/trained_models/OTS.pkl' # ffa.pk파일을 일단 사용해봤음 ITS,OTS로 사용 가능하지만 결과가 이상함.
checkpoint = torch.load(checkpoint_path)

# Load the state_dict from checkpoint
net.load_state_dict(checkpoint['model']) #일단 주석 처리했는데 원래는 load를 살리는게 맞음.

# Load the input image
image_path = 'C:/test/test2.jpg'
image = Image.open(image_path).convert('RGB')

# Preprocess the image
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
input_image = transform(image).unsqueeze(0)

# Perform fog removal
with torch.no_grad():
    output_image = net(input_image)

# Post-process the output image
output_image = output_image.squeeze(0).detach().cpu()
output_image = transforms.ToPILImage()(output_image)

# Save the output image
output_image.save('C:/test/C2PNet_output1.jpg')

if __name__ == "__main__":
    net = C2PNet(gps=3, blocks=19)
    print(net)

这是我的代码。哪个部分出了问题呢？

**Comment by chartgod** [comment]
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image

def default_conv(in_channels, out_channels, kernel_size, bias=True):
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=(kernel_size // 2), bias=bias)


class CALayer(nn.Module):
    def __init__(self, channel):
        super(CALayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ca = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PDU(nn.Module):  # physical block
    def __init__(self, channel):
        super(PDU, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ka = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )
        self.td = nn.Sequential(
            default_conv(channel, channel, 3),
            default_conv(channel, channel // 8, 3),
            nn.ReLU(inplace=True),
            default_conv(channel // 8, channel, 3),
            nn.Sigmoid()
        )

    def forward(self, x):
        a = self.avg_pool(x)
        a = self.ka(a)
        t = self.td(x)
        j = torch.mul((1 - t), a) + torch.mul(t, x)
        return j


class Block(nn.Module):  # origin
    def __init__(self, conv, dim, kernel_size, ):
        super(Block, self).__init__()
        self.conv1 = conv(dim, dim, kernel_size, bias=True)
        self.act1 = nn.ReLU(inplace=True)
        self.conv2 = conv(dim, dim, kernel_size, bias=True)
        self.calayer = CALayer(dim)
        self.pdu = PDU(dim)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x
        res = self.conv2(res)
        res = self.calayer(res)
        res = self.pdu(res)
        res += x
        return res


class Group(nn.Module):
    def __init__(self, conv, dim, kernel_size, blocks):
        super(Group, self).__init__()
        modules = [Block(conv, dim, kernel_size) for _ in range(blocks)]
        modules.append(conv(dim, dim, kernel_size))
        self.gp = nn.Sequential(*modules)

    def forward(self, x):
        res = self.gp(x)
        res += x
        return res


class C2PNet(nn.Module):
    def __init__(self, gps, blocks, conv=default_conv):
        super(C2PNet, self).__init__()
        self.gps = gps
        self.dim = 64
        kernel_size = 3
        pre_process = [conv(3, self.dim, kernel_size)]
        assert self.gps == 3
        self.g1 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g2 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g3 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.ca = nn.Sequential(*[
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(self.dim * self.gps, self.dim // 16, 1, padding=0),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.dim // 16, self.dim * self.gps, 1, padding=0, bias=True),
            nn.Sigmoid()
        ])
        self.pdu = PDU(self.dim)

        post_precess = [
            conv(self.dim, self.dim, kernel_size),
            conv(self.dim, 3, kernel_size)]

        self.pre = nn.Sequential(*pre_process)
        self.post = nn.Sequential(*post_precess)

    def forward(self, x1):
        x = self.pre(x1)
        res1 = self.g1(x)
        res2 = self.g2(res1)
        res3 = self.g3(res2)
        w = self.ca(torch.cat([res1, res2, res3], dim=1))
        w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]
        out = w[:, 0, ::] * res1 + w[:, 1, ::] * res2 + w[:, 2, ::] * res3
        out = self.pdu(out)
        x = self.post(out)
        return x + x1

# Load the C2PNet model
net = C2PNet(gps=3, blocks=19)

# Load the checkpoint
checkpoint_path = 'C:/C2PNet-main/trained_models/OTS.pkl' # ffa.pk파일을 일단 사용해봤음 ITS,OTS로 사용 가능하지만 결과가 이상함.
checkpoint = torch.load(checkpoint_path)

# Load the state_dict from checkpoint
net.load_state_dict(checkpoint['model']) #일단 주석 처리했는데 원래는 load를 살리는게 맞음.

# Load the input image
image_path = 'C:/test/test2.jpg'
image = Image.open(image_path).convert('RGB')

# Preprocess the image
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
input_image = transform(image).unsqueeze(0)

# Perform fog removal
with torch.no_grad():
    output_image = net(input_image)

# Post-process the output image
output_image = output_image.squeeze(0).detach().cpu()
output_image = transforms.ToPILImage()(output_image)

# Save the output image
output_image.save('C:/test/C2PNet_output1.jpg')

if __name__ == "__main__":
    net = C2PNet(gps=3, blocks=19)
    print(net)

这是我的代码。哪个部分出了问题呢？

**Comment by chartgod** [comment]
`import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image

def default_conv(in_channels, out_channels, kernel_size, bias=True):
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=(kernel_size // 2), bias=bias)


class CALayer(nn.Module):
    def __init__(self, channel):
        super(CALayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ca = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PDU(nn.Module):  # physical block
    def __init__(self, channel):
        super(PDU, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ka = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )
        self.td = nn.Sequential(
            default_conv(channel, channel, 3),
            default_conv(channel, channel // 8, 3),
            nn.ReLU(inplace=True),
            default_conv(channel // 8, channel, 3),
            nn.Sigmoid()
        )

    def forward(self, x):
        a = self.avg_pool(x)
        a = self.ka(a)
        t = self.td(x)
        j = torch.mul((1 - t), a) + torch.mul(t, x)
        return j


class Block(nn.Module):  # origin
    def __init__(self, conv, dim, kernel_size, ):
        super(Block, self).__init__()
        self.conv1 = conv(dim, dim, kernel_size, bias=True)
        self.act1 = nn.ReLU(inplace=True)
        self.conv2 = conv(dim, dim, kernel_size, bias=True)
        self.calayer = CALayer(dim)
        self.pdu = PDU(dim)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x
        res = self.conv2(res)
        res = self.calayer(res)
        res = self.pdu(res)
        res += x
        return res


class Group(nn.Module):
    def __init__(self, conv, dim, kernel_size, blocks):
        super(Group, self).__init__()
        modules = [Block(conv, dim, kernel_size) for _ in range(blocks)]
        modules.append(conv(dim, dim, kernel_size))
        self.gp = nn.Sequential(*modules)

    def forward(self, x):
        res = self.gp(x)
        res += x
        return res


class C2PNet(nn.Module):
    def __init__(self, gps, blocks, conv=default_conv):
        super(C2PNet, self).__init__()
        self.gps = gps
        self.dim = 64
        kernel_size = 3
        pre_process = [conv(3, self.dim, kernel_size)]
        assert self.gps == 3
        self.g1 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g2 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g3 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.ca = nn.Sequential(*[
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(self.dim * self.gps, self.dim // 16, 1, padding=0),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.dim // 16, self.dim * self.gps, 1, padding=0, bias=True),
            nn.Sigmoid()
        ])
        self.pdu = PDU(self.dim)

        post_precess = [
            conv(self.dim, self.dim, kernel_size),
            conv(self.dim, 3, kernel_size)]

        self.pre = nn.Sequential(*pre_process)
        self.post = nn.Sequential(*post_precess)

    def forward(self, x1):
        x = self.pre(x1)
        res1 = self.g1(x)
        res2 = self.g2(res1)
        res3 = self.g3(res2)
        w = self.ca(torch.cat([res1, res2, res3], dim=1))
        w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]
        out = w[:, 0, ::] * res1 + w[:, 1, ::] * res2 + w[:, 2, ::] * res3
        out = self.pdu(out)
        x = self.post(out)
        return x + x1

# Load the C2PNet model
net = C2PNet(gps=3, blocks=19)

# Load the checkpoint
checkpoint_path = 'C:/C2PNet-main/trained_models/OTS.pkl' # ffa.pk파일을 일단 사용해봤음 ITS,OTS로 사용 가능하지만 결과가 이상함.
checkpoint = torch.load(checkpoint_path)

# Load the state_dict from checkpoint
net.load_state_dict(checkpoint['model']) #일단 주석 처리했는데 원래는 load를 살리는게 맞음.

# Load the input image
image_path = 'C:/test/test2.jpg'
image = Image.open(image_path).convert('RGB')

# Preprocess the image
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
input_image = transform(image).unsqueeze(0)

# Perform fog removal
with torch.no_grad():
    output_image = net(input_image)

# Post-process the output image
output_image = output_image.squeeze(0).detach().cpu()
output_image = transforms.ToPILImage()(output_image)

# Save the output image
output_image.save('C:/test/C2PNet_output1.jpg')

if __name__ == "__main__":
    net = C2PNet(gps=3, blocks=19)
    print(net)

`
这是我的代码。哪个部分出了问题呢？

**Comment by chartgod** [comment]
def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PDU(nn.Module):  # physical block
    def __init__(self, channel):
        super(PDU, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ka = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )
        self.td = nn.Sequential(
            default_conv(channel, channel, 3),
            default_conv(channel, channel // 8, 3),
            nn.ReLU(inplace=True),
            default_conv(channel // 8, channel, 3),
            nn.Sigmoid()
        )

    def forward(self, x):
        a = self.avg_pool(x)
        a = self.ka(a)
        t = self.td(x)
        j = torch.mul((1 - t), a) + torch.mul(t, x)
        return j


class Block(nn.Module):  # origin
    def __init__(self, conv, dim, kernel_size, ):
        super(Block, self).__init__()
        self.conv1 = conv(dim, dim, kernel_size, bias=True)
        self.act1 = nn.ReLU(inplace=True)
        self.conv2 = conv(dim, dim, kernel_size, bias=True)
        self.calayer = CALayer(dim)
        self.pdu = PDU(dim)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x
        res = self.conv2(res)
        res = self.calayer(res)
        res = self.pdu(res)
        res += x
        return res


class Group(nn.Module):
    def __init__(self, conv, dim, kernel_size, blocks):
        super(Group, self).__init__()
        modules = [Block(conv, dim, kernel_size) for _ in range(blocks)]
        modules.append(conv(dim, dim, kernel_size))
        self.gp = nn.Sequential(*modules)

    def forward(self, x):
        res = self.gp(x)
        res += x
        return res


class C2PNet(nn.Module):
    def __init__(self, gps, blocks, conv=default_conv):
        super(C2PNet, self).__init__()
        self.gps = gps
        self.dim = 64
        kernel_size = 3
        pre_process = [conv(3, self.dim, kernel_size)]
        assert self.gps == 3
        self.g1 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g2 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g3 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.ca = nn.Sequential(*[
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(self.dim * self.gps, self.dim // 16, 1, padding=0),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.dim // 16, self.dim * self.gps, 1, padding=0, bias=True),
            nn.Sigmoid()
        ])
        self.pdu = PDU(self.dim)

        post_precess = [
            conv(self.dim, self.dim, kernel_size),
            conv(self.dim, 3, kernel_size)]

        self.pre = nn.Sequential(*pre_process)
        self.post = nn.Sequential(*post_precess)

    def forward(self, x1):
        x = self.pre(x1)
        res1 = self.g1(x)
        res2 = self.g2(res1)
        res3 = self.g3(res2)
        w = self.ca(torch.cat([res1, res2, res3], dim=1))
        w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]
        out = w[:, 0, ::] * res1 + w[:, 1, ::] * res2 + w[:, 2, ::] * res3
        out = self.pdu(out)
        x = self.post(out)
        return x + x1

# Load the C2PNet model
net = C2PNet(gps=3, blocks=19)

# Load the checkpoint
checkpoint_path = 'C:/C2PNet-main/trained_models/OTS.pkl' # ffa.pk파일을 일단 사용해봤음 ITS,OTS로 사용 가능하지만 결과가 이상함.
checkpoint = torch.load(checkpoint_path)

# Load the state_dict from checkpoint
net.load_state_dict(checkpoint['model']) #일단 주석 처리했는데 원래는 load를 살리는게 맞음.

# Load the input image
image_path = 'C:/test/test2.jpg'
image = Image.open(image_path).convert('RGB')

# Preprocess the image
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
input_image = transform(image).unsqueeze(0)

# Perform fog removal
with torch.no_grad():
    output_image = net(input_image)

# Post-process the output image
output_image = output_image.squeeze(0).detach().cpu()
output_image = transforms.ToPILImage()(output_image)

# Save the output image
output_image.save('C:/test/C2PNet_output1.jpg')

if __name__ == "__main__":
    net = C2PNet(gps=3, blocks=19)
    print(net)

**Comment by chartgod** [comment]
`import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image

def default_conv(in_channels, out_channels, kernel_size, bias=True):
    return nn.Conv2d(in_channels, out_channels, kernel_size, padding=(kernel_size // 2), bias=bias)


class CALayer(nn.Module):
    def __init__(self, channel):
        super(CALayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ca = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.ca(y)
        return x * y


class PDU(nn.Module):  # physical block
    def __init__(self, channel):
        super(PDU, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.ka = nn.Sequential(
            nn.Conv2d(channel, channel // 8, 1, padding=0, bias=True),
            nn.ReLU(inplace=True),
            nn.Conv2d(channel // 8, channel, 1, padding=0, bias=True),
            nn.Sigmoid()
        )
        self.td = nn.Sequential(
            default_conv(channel, channel, 3),
            default_conv(channel, channel // 8, 3),
            nn.ReLU(inplace=True),
            default_conv(channel // 8, channel, 3),
            nn.Sigmoid()
        )

    def forward(self, x):
        a = self.avg_pool(x)
        a = self.ka(a)
        t = self.td(x)
        j = torch.mul((1 - t), a) + torch.mul(t, x)
        return j


class Block(nn.Module):  # origin
    def __init__(self, conv, dim, kernel_size, ):
        super(Block, self).__init__()
        self.conv1 = conv(dim, dim, kernel_size, bias=True)
        self.act1 = nn.ReLU(inplace=True)
        self.conv2 = conv(dim, dim, kernel_size, bias=True)
        self.calayer = CALayer(dim)
        self.pdu = PDU(dim)

    def forward(self, x):
        res = self.act1(self.conv1(x))
        res = res + x
        res = self.conv2(res)
        res = self.calayer(res)
        res = self.pdu(res)
        res += x
        return res


class Group(nn.Module):
    def __init__(self, conv, dim, kernel_size, blocks):
        super(Group, self).__init__()
        modules = [Block(conv, dim, kernel_size) for _ in range(blocks)]
        modules.append(conv(dim, dim, kernel_size))
        self.gp = nn.Sequential(*modules)

    def forward(self, x):
        res = self.gp(x)
        res += x
        return res


class C2PNet(nn.Module):
    def __init__(self, gps, blocks, conv=default_conv):
        super(C2PNet, self).__init__()
        self.gps = gps
        self.dim = 64
        kernel_size = 3
        pre_process = [conv(3, self.dim, kernel_size)]
        assert self.gps == 3
        self.g1 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g2 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.g3 = Group(conv, self.dim, kernel_size, blocks=blocks)
        self.ca = nn.Sequential(*[
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(self.dim * self.gps, self.dim // 16, 1, padding=0),
            nn.ReLU(inplace=True),
            nn.Conv2d(self.dim // 16, self.dim * self.gps, 1, padding=0, bias=True),
            nn.Sigmoid()
        ])
        self.pdu = PDU(self.dim)

        post_precess = [
            conv(self.dim, self.dim, kernel_size),
            conv(self.dim, 3, kernel_size)]

        self.pre = nn.Sequential(*pre_process)
        self.post = nn.Sequential(*post_precess)

    def forward(self, x1):
        x = self.pre(x1)
        res1 = self.g1(x)
        res2 = self.g2(res1)
        res3 = self.g3(res2)
        w = self.ca(torch.cat([res1, res2, res3], dim=1))
        w = w.view(-1, self.gps, self.dim)[:, :, :, None, None]
        out = w[:, 0, ::] * res1 + w[:, 1, ::] * res2 + w[:, 2, ::] * res3
        out = self.pdu(out)
        x = self.post(out)
        return x + x1

# Load the C2PNet model
net = C2PNet(gps=3, blocks=19)

# Load the checkpoint
checkpoint_path = 'C:/C2PNet-main/trained_models/OTS.pkl' # ffa.pk파일을 일단 사용해봤음 ITS,OTS로 사용 가능하지만 결과가 이상함.
checkpoint = torch.load(checkpoint_path)

# Load the state_dict from checkpoint
net.load_state_dict(checkpoint['model']) #일단 주석 처리했는데 원래는 load를 살리는게 맞음.

# Load the input image
image_path = 'C:/test/test2.jpg'
image = Image.open(image_path).convert('RGB')

# Preprocess the image
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
input_image = transform(image).unsqueeze(0)

# Perform fog removal
with torch.no_grad():
    output_image = net(input_image)

# Post-process the output image
output_image = output_image.squeeze(0).detach().cpu()
output_image = transforms.ToPILImage()(output_image)

# Save the output image
output_image.save('C:/test/C2PNet_output1.jpg')

if __name__ == "__main__":
    net = C2PNet(gps=3, blocks=19)
    print(net)
`

**Comment by chartgod** [comment]
我想共享代码，直接写在评论上就可以吗？

**Comment by chartgod** [comment]
[C2PNet.txt](https://github.com/YuZheng9/C2PNet/files/11945784/default.txt)

这是我的代码。

**Comment by tongchangD** [comment]
@chartgod  给你一个极简测试的代码
```
import torch
from PIL import Image
from models.C2PNet import C2PNet
import torchvision.transforms as tfs
net=C2PNet(gps=3, blocks=19).to('cuda:0' if torch.cuda.is_available() else 'cpu').load_state_dict(torch.load('trained_models/OTS.pkl')['model'])
Image.fromarray(torch.squeeze((tfs.ToTensor()(Image.open("./1.png").convert('RGB'))[None, ::].to('cuda:0' if torch.cuda.is_available() else 'cpu')).clamp(0, 1).cpu()).mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to("cpu", torch.uint8).numpy()).save("./out1.png")
```

**Comment by chartgod** [comment]
谢谢！

**Comment by zhunzhun123** [comment]
> 请问对于真实数据去雾，在做合成雾的时候，除了有[RGB和模拟大气散射模型](https://github.com/RQ-Wu/RIDCP_dehazing/issues/10)来添加雾，还有其他比价好的方案来添加雾气吗，请问有试过利用Photoshop来合成真实雾最终用于去雾吗

您好 我也有相同的疑惑 您找到更好的解决方法了么
