### ISSUE TITLE
about OTS.lmdb

### ISSUE THREAD

**Issue by chensming** [YuZheng9/C2PNet#13]
您好，我通过您给的连接去下载数据集，好像只有ITS和SOTS数据集，请问如何得到OTS.LMDB呢？
另外我还想问下，如何将图片转为imdb格式呢？提前感谢您的解答~
![image](https://github.com/YuZheng9/C2PNet/assets/45591767/0c1f554d-4beb-4990-93b9-b7d2d9517493)

**Comment by YuZheng9** [comment]
> 如何

你好，ots.lmdb文件由于太大了，实在没办法上传，你可以仿照its.lmdb文件生成。
此外lmdb文件可以通过`create_lmdb.py`生成
