### ISSUE TITLE
您好，想问一下您关于训练自己数据集的步骤

### ISSUE THREAD

**Issue by liu0619** [YuZheng9/C2PNet#14]
您好，我想问一下如何用自己的数据集进行训练呢？先生成LMDB文件吗？那负样本怎么生成呢？

**Comment by YuZheng9** [comment]
你可以根据自己的想法来选择不同的预训练模型，得到不同难度的负样本，然后制作成lmdb文件

**Comment by YuZheng9** [comment]
> 您好，我想问一下如何用自己的数据集进行训练呢？先生成LMDB文件吗？那负样本怎么生成呢？

你可以根据自己的想法来选择不同的预训练模型，得到不同难度的负样本，然后制作成lmdb文件

**Comment by tongchangD** [comment]
> > 您好，我想问一下如何用自己的数据集进行训练呢？先生成LMDB文件吗？那负样本怎么生成呢？
> 
> 你可以根据自己的想法来选择不同的预训练模型，得到不同难度的负样本，然后制作成lmdb文件

@YuZheng9  我理解您的意思是，利用市面其他开源模型跑出一些结果，作为负样本或负例，而真正的GT还是真正的GT文件，是得模型生成结果与GT越近与其他结果越远。
请问我理解的对吗
祝好
tongchangD
