### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by fei1998** [YuZheng9/C2PNet#2]
Thank you so much for your awesome work! I would like to ask when the training code will be released.
Best wishes.

**Comment by YuZheng9** [comment]
> Thank you so much for your awesome work! I would like to ask when the training code will be released. Best wishes.

The training code will be released after being organized.

**Comment by YuZheng9** [comment]
> Thank you so much for your awesome work! I would like to ask when the training code will be released. Best wishes.

We release training code.
