### ISSUE TITLE
关于微调的方式以及OTS.lmdb数据集

### ISSUE THREAD

**Issue by Healer-h-bit** [YuZheng9/C2PNet#23]
您好，请问您可以将制作的OTS.lmdb的数据集也上传到百度网盘吗？万分感谢！祝科研顺利！

**Comment by Healer-h-bit** [comment]
请问您能分享一下微调的方法吗？谢谢！

**Comment by YuZheng9** [comment]
OTS.lmdb 太大了无法上传到云盘上，你可以按照论文中的方法自己制作。
关于fattal‘s dataset上微调的方法，用了ITS和OTS联合训练。

**Comment by LiaoRF** [comment]
您好：      我已收到您的来信，谢谢！                                           廖瑞丰

**Comment by Healer-h-bit** [comment]
谢谢您的解答，还有一个问题就是请问联合训练是比如在ITS训练100000轮，然后用训练完的模型再在OTS上训练100000轮嘛？

**Comment by zhaofengnain** [comment]
> 您好，请问您可以将制作的OTS.lmdb的数据集也上传到百度网盘吗？万分感谢！祝科研顺利！

你好，请问制作数据集的create_lmdb.py文件如何运行的，我运行会报错

**Comment by LiaoRF** [comment]
您好：      我已收到您的来信，谢谢！                                           廖瑞丰
