### ISSUE TITLE
训练运行报错

### ISSUE THREAD

**Issue by miaofc1998** [YuZheng9/C2PNet#27]
你好，为什么在ITS数据集上训练时，复制的命令报错。
model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk
2
crop size 240
crop size whole img
crop size whole img
log_dir : logs/'its_train'_C2PNet_3_19_default_clcr
model_name: 'its_train'_C2PNet_3_19_default_clcr
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    loader_train = loaders_[opt.trainset]
KeyError: "'its_train'"

**Comment by zhaofengnain** [comment]
> 你好，为什么在ITS数据集上训练时，复制的命令报错。 model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 crop size 240 crop size whole img crop size whole img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name: 'its_train'_C2PNet_3_19_default_clcr Traceback (most recent call last): File "main.py", line 172, in loader_train = loaders_[opt.trainset] KeyError: "'its_train'"

这个问题你解决了么？
@miaofc1998

**Comment by miaofc1998** [comment]
把“”去了试试

> > 好，为什么在ITS数据集上你训练时，复制的命令报错。 model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 裁剪尺寸 240 裁剪尺寸 整个img 裁剪尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' _C2PNet_3_19_default_clcr 回溯（最近一次调用）：文件“main.py”，第 172 行，在 loader_train = loaders_ [opt.trainset] KeyError：“'its_train'”
> 
> 这个问题你解决了吗？ @miaofc1998

**Comment by miaofc1998** [comment]
> > model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 裁剪尺寸 240 裁剪尺寸 整个img 裁剪尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' _C2PNet_3_19_default_clcr 回溯（最近一次调用）：文件“main.py”，第172行，在 loader_train = loaders_ [opt.trainset] KeyError：“'its_train'”
> 
> 这个问题你解决了吗？ @miaofc1998
把‘’去掉试试，应该是字符的原因

**Comment by miaofc1998** [comment]
> > model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 尺寸尺寸 240 尺寸尺寸 整个img 尺寸尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' C2PNet_3_19_default_clcr 回（最近一次调用）：_文件“main. py ”，第172行，在 loader_train = loaders_ [opt.trainset] KeyError：“'its_train'”
> 
> 这个问题你解决了吗？ @miaofc1998

把‘’去掉试试，应该是字符的原因

**Comment by zhaofengnain** [comment]
> 把“”去了试试
> 
> > > 好，为什么在ITS数据集上你训练时，复制的命令报错。 model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 裁剪尺寸 240 裁剪尺寸 整个img 裁剪尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' _C2PNet_3_19_default_clcr 回溯（最近一次调用）：文件“main.py”，第 172 行，在 loader_train = loaders_ [opt.trainset] KeyError：“'its_train'”
> > 
> > 
> > 这个问题你解决了吗？ @miaofc1998

这个问题解决了，但是后面运行main.py文件的时候，请教一下n1-n6的这个六个路径你是怎么处理的
@miaofc1998

**Comment by miaofc1998** [comment]
后面我没跑了，瞅了一下，负样本处理完太大了，没足够的资源




苗凤昌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuZheng9/C2PNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuZheng9/C2PNet] 训练运行报错 (Issue #27)





  
把“”去了试试
   
好，为什么在ITS数据集上你训练时，复制的命令报错。 model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 裁剪尺寸 240 裁剪尺寸 整个img 裁剪尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' C2PNet_3_19_default_clcr 回溯（最近一次调用）：文件“main.py”，第 172 行，在 loader_train = loaders [opt.trainset] KeyError：“'its_train'”
  
这个问题你解决了吗？ @miaofc1998
   
这个问题解决了，但是后面运行main.py文件的时候，请教一下n1-n6的这个六个路径你是怎么处理的
 @miaofc1998

**Comment by miaofc1998** [comment]
> > 把“”去了试试
> > > > 好，为什么在ITS数据集上你训练时，复制的命令报错。 model_dir: ./trained_models/'its_train'_C2PNet_3_19_default_clcr.pk 2 裁剪尺寸 240 裁剪尺寸 整个img 裁剪尺寸 整个img log_dir : logs/'its_train'_C2PNet_3_19_default_clcr model_name : 'its_train' _C2PNet_3_19_default_clcr 回溯（最近一次调用）：文件“main.py”，第 172 行，在 loader_train = loaders_ [opt.trainset] KeyError：“'its_train'”
> > > 
> > > 
> > > 这个问题你解决了吗？ @miaofc1998
> 
> 这个问题解决了，但是后面运行main.py文件的时候，请教一下n1-n6的这个六个路径你是怎么处理的 @miaofc1998
后面没跑了，负样本处理出来太大了，计算资源不允许

**Comment by zhaofengnain** [comment]
![Picture1](https://github.com/YuZheng9/C2PNet/assets/68000013/177f5509-1c98-4d6a-a53a-af4628d287f7)
需要很大的计算资源么？我想租服务器试一下，请问这六个路径是什么意思呢？是用来存放六种方法处理后的去雾图片作为数据集么，
@miaofc1998

**Comment by miaofc1998** [comment]
> ![图片1](https://private-user-images.githubusercontent.com/68000013/292756857-177f5509-1c98-4d6a-a53a-af4628d287f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDg3MzgsIm5iZiI6MTcwMzUwODQzOCwicGF0aCI6Ii82ODAwMDAxMy8yOTI3NTY4NTctMTc3ZjU1MDktMWM5OC00ZDZhLWE1M2EtYWY0NjI4ZDI4N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEyNDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmM2VjMjQ5ODhlNjZmMTkxODdkODAxYjdiY2ViMDU1YjQ2OTU3OTIwMmVkYmJmZTU0MGExMjZkOTNjNzNhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCiAVnO1WailUv6-GVEhyXJWUaPTqSP5HVlkYTre40Q) 需要大量的计算资源么？我想租服务器试一下，请问这六个路径是什么意思呢？是用来搁置六种方法处理后去雾图片作为数据集么， @miaofc1998

作者说的意思，应该就是6个不同模型处理后的图片作为负样本吧

**Comment by zhaofengnain** [comment]
> > ![图片1](https://private-user-images.githubusercontent.com/68000013/292756857-177f5509-1c98-4d6a-a53a-af4628d287f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDg3MzgsIm5iZiI6MTcwMzUwODQzOCwicGF0aCI6Ii82ODAwMDAxMy8yOTI3NTY4NTctMTc3ZjU1MDktMWM5OC00ZDZhLWE1M2EtYWY0NjI4ZDI4N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEyNDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmM2VjMjQ5ODhlNjZmMTkxODdkODAxYjdiY2ViMDU1YjQ2OTU3OTIwMmVkYmJmZTU0MGExMjZkOTNjNzNhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCiAVnO1WailUv6-GVEhyXJWUaPTqSP5HVlkYTre40Q) 需要大量的计算资源么？我想租服务器试一下，请问这六个路径是什么意思呢？是用来搁置六种方法处理后去雾图片作为数据集么， @miaofc1998
> 
> 作者说的意思，应该就是6个不同模型处理后的图片作为负样本吧

那是要用六个模型先去处理图片生成负样本么？这个任务量太大了吧， @miaofc1998

**Comment by miaofc1998** [comment]
> > > ![图片1](https://private-user-images.githubusercontent.com/68000013/292756857-177f5509-1c98-4d6a-a53a-af4628d287f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDg3MzgsIm5iZiI6MTcwMzUwODQzOCwicGF0aCI6Ii82ODAwMDAxMy8yOTI3NTY4NTctMTc3ZjU1MDktMWM5OC00ZDZhLWE1M2EtYWY0NjI4ZDI4N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEyNDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmM2VjMjQ5ODhlNjZmMTkxODdkODAxYjdiY2ViMDU1YjQ2OTU3OTIwMmVkYmJmZTU0MGExMjZkOTNjNzNhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCiAVnO1WailUv6-GVEhyXJWUaPTqSP5HVlkYTre40Q) 需要大量的计算资源么？我想租服务器试一下，请问这六个路径是什么意思呢？是用来搁置六种方法处理后去雾图片作为数据集么， @miaofc1998
> > 
> > 
> > 作者说的意思，应该就是6个不同模型处理后的图片作为负样本吧
> 
> 那是要用六个模型先去处理图片生成负样本么？这个任务量太大了吧， @miaofc1998

应该是这样的意思，我没仔细看，后面也没跑这个。感觉你可以少一点负样本试试，毕竟你只是想调试

**Comment by wenchao-tech** [comment]
你好，能请问一下用训练出来的模型做测试为什么会报错吗？路径也修改了
![c68fdcf6-c193-4046-8c2e-4469f807c65e](https://github.com/user-attachments/assets/dffcd03a-00bd-425e-a370-129c6facfdd4)

**Comment by miaofc1998** [comment]
我后来没继续看这个




苗凤昌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuZheng9/C2PNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuZheng9/C2PNet] 训练运行报错 (Issue #27)





 
你好，能请问一下用训练出来的模型做测试为什么会报错吗？路径也修改了
 c68fdcf6-c193-4046-8c2e-4469f807c65e.png (view on web)

**Comment by miaofc1998** [comment]
> 你好，能请问一下用训练出来的模型做测试为什么会报错吗？路径也修改了 ![c68fdcf6-c193-4046-8c2e-4469f807c65e](https://private-user-images.githubusercontent.com/81458445/396816321-dffcd03a-00bd-425e-a370-129c6facfdd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTM2NzIsIm5iZiI6MTczNDUxMzM3MiwicGF0aCI6Ii84MTQ1ODQ0NS8zOTY4MTYzMjEtZGZmY2QwM2EtMDBiZC00MjVlLWEzNzAtMTI5YzZmYWNmZGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZmMzMmExYjM4YmIxZTgwYTMzY2ZiODA2ODdkOWFiNmU1ZWIyOGNiOTkyMDhlYWQ2ZmE4YzUzMzJmODJlM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nmpb2x8OsvxSBeMaPoxRTciyU1qGM3F4088sL_lM2hE)

这个好像是可以的吧，记不清了，后来没继续看这个模型

**Comment by wenchao-tech** [comment]
![image](https://github.com/user-attachments/assets/b404e961-2e0b-42c5-88ab-d5ccdb28601c)
你好，运行出来显示这个错误，应该就是这个模型用不了诶？

**Comment by wenchao-tech** [comment]
非常感谢您的回答，我再去问下别人试试。

**Comment by miaofc1998** [comment]
> ![image](https://private-user-images.githubusercontent.com/81458445/396841243-b404e961-2e0b-42c5-88ab-d5ccdb28601c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTQwMjQsIm5iZiI6MTczNDUxMzcyNCwicGF0aCI6Ii84MTQ1ODQ0NS8zOTY4NDEyNDMtYjQwNGU5NjEtMmUwYi00MmM1LTg4YWItZDVjY2RiMjg2MDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTZmYWI5YWQ1NmRlODg1YTA1OTU0NmExOGU5ZTIxN2FlYjEyNmY3OGY0YjdmZmQ3NDczYTU2ZGM2YTQ2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C4R4Cejt8HjO-dyHXwVXIERJFQwXuhWyOaez30OHk74) 你好，运行出来显示这个错误，应该就是这个模型用不了诶？

模型加载出了问题，他模型是能用的

**Comment by wenchao-tech** [comment]
对的，他给的那两个ITS.pkl和OTS.pkl是可以用的，但现在想问的是用作者代码训出来的模型好像替换不了。

**Comment by GuoZengyi** [comment]
> 对的，他给的那两个ITS.pkl和OTS.pkl是可以用的，但现在想问的是用作者代码训出来的模型好像替换不了。

您好，我现在也遇到了同样的问题，请问您后来解决了吗？
