### ISSUE TITLE
NH-HAZE2

### ISSUE THREAD

**Issue by it-hao** [YuZheng9/C2PNet#3]
请问一下，论文中的NH-HAZE2的数据哪里可以下载，还有就是其他方法在该数据集上的结果是怎么得到的？谢谢~

**Comment by YuZheng9** [comment]
> 请问一下，论文中的NH-HAZE2的数据哪里可以下载，还有就是其他方法在该数据集上的结果是怎么得到的？谢谢~
NH-HAZE2数据集在NTIRE2021的图像去雾赛道上可以下载，其他方法在该数据集上的结果由我们在保证公平的情况下训练得到。

**Comment by YuZheng9** [comment]
> 请问一下，论文中的NH-HAZE2的数据哪里可以下载，还有就是其他方法在该数据集上的结果是怎么得到的？谢谢~

NH-HAZE2数据集在NTIRE2021的图像去雾赛道上可以下载，其他方法在该数据集上的结果由我们在确保公平的条件下自己训练得到。

**Comment by cs-hao** [comment]
不好意思，NH-HAZE2数据集好像现在下载不了，您能不能提供一下，还有就是该数据集并没有提供验证集和测试集的GT，您是拿前面20张训练，后面5张做测试的  还是说你采取了新的办法？谢谢~

**Comment by it-hao** [comment]
不好意思，NH-HAZE2数据集好像现在下载不了，您能不能提供一下，还有就是该数据集并没有提供验证集和测试集的GT，您是拿前面20张训练，后面5张做测试的 还是说你采取了新的办法？谢谢~

**Comment by YuZheng9** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，我们在NH-Haze2上是拿前20张训练，后面5张进行测试。我最近比较忙，暂时没空整理数据集，等我空下来会把模型和数据集整理好放到github上的。
    
        
            
        
    
    
    
    

    

    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Hao ***@***.***>
            
        
      
      
        
         Date 
        
        
        04/14/2023 10:00
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [YuZheng9/C2PNet] NH-HAZE2 (Issue #3)
        
      
    
  
  
不好意思，NH-HAZE2数据集好像现在下载不了，您能不能提供一下，还有就是该数据集并没有提供验证集和测试集的GT，您是拿前面20张训练，后面5张做测试的 还是说你采取了新的办法？谢谢~

**Comment by ZHB2333** [comment]
> 请问一下，论文中的NH-HAZE2的数据哪里可以下载，还有就是其他方法在该数据集上的结果是怎么得到的？谢谢~

请问你找到数据集了么，NTIRE2021的图像去雾赛道的下载链接打不开了
