### ISSUE TITLE
about last skip-connection in the network

### ISSUE THREAD

**Issue by 848475885** [YuZheng9/C2PNet#4]
Hi, thank you for the share of your awesome work! I have a small question about your code, according to Figure 2 in your paper, the features of the first 3*3 convolution are connected to the final output of the last 3*3 convolution. However, in your code, it appears that the input itself is connected to the last convolution instead. Could you explain why this is?

**Comment by YuZheng9** [comment]
> Hi, thank you for the share of your awesome work! I have a small question about your code, according to Figure 2 in your paper, the features of the first 3_3 convolution are connected to the final output of the last 3_3 convolution. However, in your code, it appears that the input itself is connected to the last convolution instead. Could you explain why this is?

Thanks for the reminder, it has been modified.
