### ISSUE TITLE
About the difficulty level

### ISSUE THREAD

**Issue by SmileShaun** [YuZheng9/C2PNet#7]
It's a really good job！！！But I have a question.
In the **main.py** file, **diff_list[]** in **curriculum_weight()** function has 6 fixed PSNR. I think the negatives PSNR of each training picture may be different, so why are there 6 fixed values here?
Thank you for your answer!

**Comment by YuZheng9** [comment]
> It's a really good job！！！But I have a question. In the **main.py** file, **diff_list[]** in **curriculum_weight()** function has 6 fixed PSNR. I think the negatives PSNR of each training picture may be different, so why are there 6 fixed values here? Thank you for your answer!

We calculate the average PSNR of each type of negative (e.g., FFA,GDN,etc) as a measure of difficulty.

**Comment by SmileShaun** [comment]
> > It's a really good job！！！But I have a question. In the **main.py** file, **diff_list[]** in **curriculum_weight()** function has 6 fixed PSNR. I think the negatives PSNR of each training picture may be different, so why are there 6 fixed values here? Thank you for your answer!
> 
> We calculate the average PSNR of each type of negative (e.g., FFA,GDN,etc) as a measure of difficulty.

Thanks！！
