### ISSUE TITLE
About the choice of negative

### ISSUE THREAD

**Issue by SmileShaun** [YuZheng9/C2PNet#8]
您好！我想请问一下是否可以这样选择negatives：假设我已经搭建好了一个模型，先只用L1 Loss对其进行训练，我保留了训练过程中各个Epoch的网络参数。我选择train PSNR大概为25、30、31、32、33的权重所生成的dehazed images作为negatives。这样起到的效果是否可以和从其他去雾方法生成的negatives一样呢？谢谢您的回答。

**Comment by YuZheng9** [comment]
> 您好！我想请问一下是否可以这样选择negatives：假设我已经搭建好了一个模型，先只用L1 Loss对其进行训练，我保留了训练过程中各个Epoch的网络参数。我选择train PSNR大概为25、30、31、32、33的权重所生成的dehazed images作为negatives。这样起到的效果是否可以和从其他去雾方法生成的negatives一样呢？谢谢您的回答。

你可以试试，在保持和原有的setting 难度接近的情况下做消融实验，我在补充材料里有做使用interpolate生成的退化图像作为negatives的实验，得到的效果并不好。

**Comment by SmileShaun** [comment]
> > 您好！我想请问一下是否可以这样选择negatives：假设我已经搭建好了一个模型，先只用L1 Loss对其进行训练，我保留了训练过程中各个Epoch的网络参数。我选择train PSNR大概为25、30、31、32、33的权重所生成的dehazed images作为negatives。这样起到的效果是否可以和从其他去雾方法生成的negatives一样呢？谢谢您的回答。
> 
> 你可以试试，在保持和原有的setting 难度接近的情况下做消融实验，我在补充材料里有做使用interpolate生成的退化图像作为negatives的实验，得到的效果并不好。

好的 感谢回复 谢谢谢谢！！！！！！
