### ISSUE TITLE
户外验证集上的PSNR和SSIM

### ISSUE THREAD

**Issue by mengxzh15** [YuZheng9/C2PNet#9]
Average PSNR is 34.073019217253574
Average SSIM is 0.9861119985580444
这是我使用你们的方法和权重在SOTS outdoor上测试的结果，和文中说的不一致，可否解释一下？我不认为是机器配置的差别。

**Comment by YuZheng9** [comment]
> Average PSNR is 34.073019217253574 Average SSIM is 0.9861119985580444 这是我使用你们的方法和权重在SOTS outdoor上测试的结果，和文中说的不一致，可否解释一下？我不认为是机器配置的差别。

<img width="258" alt="image" src="https://user-images.githubusercontent.com/59441984/234280603-07dc6345-6e95-4c3b-b8d6-45fe52b4cbb8.png">
<img width="244" alt="image" src="https://user-images.githubusercontent.com/59441984/234280706-03f28fda-62c7-4250-9291-bf0414c53ad2.png">
不好意思，我复现了这个问题，同一个机器两个不同的环境生成了不同的结果，我推测应该是pillow版本的问题，我现在跟新了仓库的requirement.txt。

**Comment by YuZheng9** [comment]
> Average PSNR is 34.073019217253574 Average SSIM is 0.9861119985580444 这是我使用你们的方法和权重在SOTS outdoor上测试的结果，和文中说的不一致，可否解释一下？我不认为是机器配置的差别。

你可以用`pip install Pillow==9.2.0` 解决这个问题
